# Generated by Django 4.0 on 2022-03-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
