# Generated by Django 4.0 on 2022-04-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticketdescarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdescarga',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Archivo', to='app.archivo'),
        ),
    ]
