# Generated by Django 3.2.7 on 2022-03-15 19:21

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruta', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('titulacion', models.CharField(max_length=200)),
                ('anyo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.archivo', verbose_name='Archivo')),
                ('responde_a', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.comentario', verbose_name='Responde a')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.asignatura', verbose_name='Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('tipo_reporte', models.CharField(choices=[('PLAGIO', 'Plagio'), ('ERROR', 'Error')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_academico', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, validators=[app.models.validador_email])),
                ('titulacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('foto', models.CharField(max_length=100)),
                ('contrasenha', models.CharField(max_length=100)),
                ('dinero', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('visto', models.BooleanField()),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comentario', verbose_name='Comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Propietario', to='app.usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='suscriptores',
            field=models.ManyToManyField(related_name='Suscriptores', to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
    ]
