# Generated by Django 4.0 on 2022-04-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_notificacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
    ]
