# Generated by Django 4.0 on 2022-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='comentario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_refencia',
            field=models.SmallIntegerField(default=1),
        ),
    ]
