# Generated by Django 4.0 on 2022-04-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_notificacion_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='id_refencia',
            new_name='id_referencia',
        ),
    ]
