# Generated by Django 4.0 on 2022-03-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_notificacion_id_refencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='tipo_reporte',
            new_name='tipo',
        ),
    ]
