# Generated by Django 4.0 on 2022-04-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_id_refencia_notificacion_id_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='id_referencia',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='referencia',
            field=models.CharField(default='curso', max_length=100),
        ),
    ]
