# Generated by Django 4.0 on 2022-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_notificacion_id_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
    ]
