# Generated by Django 4.0 on 2022-03-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('COMENTARIO', 'Comentario'), ('REPORTE', 'Reporte'), ('NUEVO_ALUMNO', 'Nuevo Alumno')], max_length=20),
        ),
    ]
