# Generated by Django 4.0.3 on 2022-04-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comentario_responde_a'),
        ('app', '0007_alter_notificacion_referencia'),
    ]

    operations = [
    ]
