# Generated by Django 4.0 on 2022-04-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20220419_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='app.usuario'),
        ),
    ]
