# Generated by Django 4.0 on 2022-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notificacion_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
