# Generated by Django 4.0 on 2022-04-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20220419_1936'),
        ('app', '0010_notificacion_descripcion'),
    ]

    operations = [
    ]
