# Generated by Django 4.0 on 2022-04-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ticketdescarga_archivo'),
        ('app', '0011_merge_20220422_2046'),
    ]

    operations = [
    ]
