# Generated by Django 4.0 on 2022-04-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20220425_1907'),
        ('app', '0012_merge_20220425_1942'),
    ]

    operations = [
    ]
