# Generated by Django 4.0 on 2022-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_usuario_django_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='ruta',
            field=models.FileField(upload_to='archivos/'),
        ),
    ]
