# Generated by Django 4.0 on 2022-04-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_archivo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdescarga',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Archivo', to='app.archivo'),
        ),
        migrations.AlterField(
            model_name='ticketdescarga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='app.usuario'),
        ),
    ]
