# Generated by Django 4.0 on 2022-03-19 20:43

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_archivo_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='ruta',
            field=models.FileField(upload_to=app.models.user_directory_path),
        ),
    ]
