# Generated by Django 4.0.3 on 2022-05-12 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_retiradadinero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('COMENTARIO', 'Comentario'), ('REPORTE', 'Reporte'), ('NUEVO_ALUMNO', 'Nuevo Alumno'), ('NUEVA RESEÑA', 'Resenya')], max_length=20),
        ),
        migrations.CreateModel(
            name='Resenya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
