# Generated by Django 3.2.8 on 2022-03-22 16:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_archivo_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='ruta',
            field=models.FileField(upload_to=app.models.user_directory_path, validators=[app.models.validador_archivo]),
        ),
    ]
