# Generated by Django 4.0 on 2022-05-17 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_notificacion_tipo_resenya'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiradadinero',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='retiradadinero',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
