# Generated by Django 4.0 on 2022-03-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_archivo_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='asignatura',
            field=models.ForeignKey(error_messages={'required': 'Este campo es obligatorio'}, on_delete=django.db.models.deletion.DO_NOTHING, to='app.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(error_messages={'required': 'Este campo es obligatorio'}, max_length=500),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(error_messages={'required': 'Este campo es obligatorio'}, max_length=100),
        ),
    ]
