# Generated by Django 4.0.3 on 2022-05-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_notificacion_tipo_resenya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenya',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
