# Generated by Django 4.0 on 2022-03-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_curso_asignatura_alter_curso_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='archivo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='app.archivo'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.usuario'),
        ),
    ]
