# Generated by Django 3.2.7 on 2022-05-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_comentario_texto'),
        ('app', '0020_alter_resenya_descripcion'),
    ]

    operations = [
    ]
