# Generated by Django 4.0 on 2022-06-01 12:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_20220518_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[app.models.emails_distintos]),
        ),
    ]
