# Generated by Django 4.0 on 2022-05-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_20220518_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=100)),
                ('entidad_id', models.IntegerField()),
                ('evidencia', models.CharField(max_length=600)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
