# Generated by Django 4.0 on 2022-05-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_fraude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraude',
            name='entidad_id',
            field=models.CharField(max_length=100),
        ),
    ]
