# Generated by Django 4.0 on 2022-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_reporte_archivo_alter_reporte_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
