# Generated by Django 4.0 on 2022-06-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_usuario_email'),
        ('app', '0023_alter_fraude_entidad_id'),
    ]

    operations = [
    ]
