# Generated by Django 3.2.7 on 2022-03-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
