# Generated by Django 4.0 on 2022-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_archivo_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
