# Generated by Django 4.0 on 2022-03-26 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_archivo_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
