# Generated by Django 3.2.7 on 2022-03-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_archivo_fecha_publicacion'),
        ('app', '0026_alter_usuario_foto'),
    ]

    operations = [
    ]
