# Generated by Django 3.2.7 on 2022-03-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_merge_20220327_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='prueba', max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='prueba@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='prueba', max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
