# Generated by Django 4.0 on 2022-03-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_reporte_descripcion'),
        ('app', '0028_auto_20220328_1624'),
    ]

    operations = [
    ]
