# Generated by Django 4.0.3 on 2022-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_usuario_apellidos_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
