# Generated by Django 3.2.7 on 2022-03-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_reporte_descripcion'),
        ('app', '0029_auto_20220328_2007'),
    ]

    operations = [
    ]
