# Generated by Django 4.0 on 2022-03-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_reporte_descripcion'),
        ('app', '0029_auto_20220328_2007'),
    ]

    operations = [
    ]
