# Generated by Django 4.0.3 on 2022-03-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220328_2007'),
        ('app', '0030_alter_usuario_apellidos_alter_usuario_email_and_more'),
        ('app', '0030_alter_usuario_descripcion'),
    ]

    operations = [
    ]
