# Generated by Django 3.2.7 on 2022-04-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_merge_20220329_2057'),
        ('app', '0031_merge_20220330_1833'),
        ('app', '0031_merge_20220330_1846'),
    ]

    operations = [
    ]
