# Generated by Django 4.0.3 on 2022-04-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_merge_20220330_1915'),
        ('app', '0031_alter_curso_suscriptores'),
        ('app', '0032_merge_20220402_1610'),
    ]

    operations = [
    ]
