# Generated by Django 3.2.7 on 2022-04-03 10:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_merge_20220402_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='/media/avatar.png', null=True, upload_to=app.models.image_directory_path),
        ),
    ]
