# Generated by Django 4.0.3 on 2022-04-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_merge_20220402_1937'),
        ('app', '0034_alter_usuario_foto'),
    ]

    operations = [
    ]
