# Generated by Django 4.0.3 on 2022-04-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_merge_20220404_2210'),
        ('app', '0035_merge_20220404_2215'),
    ]

    operations = [
    ]
