name: Codacy

on:
  workflow_run:
      workflows: ["Tests"]
      types:
        - completed
  push:
    branches:    
      - develop
      - main

jobs:
  codacy:
    name: Codacy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647