name: Tests

on:
  workflow_run:
      workflows: ["Commits"]
      types:
        - completed
  pull_request:
    types:
      - "opened"
      - "reopened"
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: ustudy
          POSTGRES_PASSWORD: ustudy
          POSTGRES_DB: ustudy
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    # - name: psycopg2 prerequisites
    #   run: sudo apt-get install libpq-dev
    # - name: Install dependencies
    #   run: 
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt